{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "Z9sYcDE-qV7z"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "# 1.) Import an asset price from Yahoo Finance"
      ],
      "metadata": {
        "id": "6dJuZDx9qWeM"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "pip install yfinance"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "QxUUnTVTrx3m",
        "outputId": "13a91e99-764c-4c44-8a3a-4978174a73b3"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n",
            "Collecting yfinance\n",
            "  Downloading yfinance-0.2.12-py2.py3-none-any.whl (59 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m59.2/59.2 KB\u001b[0m \u001b[31m883.8 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.4.4)\n",
            "Collecting beautifulsoup4>=4.11.1\n",
            "  Downloading beautifulsoup4-4.11.2-py3-none-any.whl (129 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m129.4/129.4 KB\u001b[0m \u001b[31m3.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.8/dist-packages (from yfinance) (4.9.2)\n",
            "Collecting cryptography>=3.3.2\n",
            "  Downloading cryptography-39.0.1-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m4.2/4.2 MB\u001b[0m \u001b[31m21.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting requests>=2.26\n",
            "  Downloading requests-2.28.2-py3-none-any.whl (62 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m62.8/62.8 KB\u001b[0m \u001b[31m2.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting frozendict>=2.3.4\n",
            "  Downloading frozendict-2.3.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (111 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m111.2/111.2 KB\u001b[0m \u001b[31m4.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.22.4)\n",
            "Collecting html5lib>=1.1\n",
            "  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m112.2/112.2 KB\u001b[0m \u001b[31m4.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (2022.7.1)\n",
            "Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from yfinance) (0.0.11)\n",
            "Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.3.5)\n",
            "Collecting soupsieve>1.2\n",
            "  Downloading soupsieve-2.4-py3-none-any.whl (37 kB)\n",
            "Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=3.3.2->yfinance) (1.15.1)\n",
            "Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)\n",
            "Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (1.15.0)\n",
            "Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)\n",
            "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (1.24.3)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.10)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2022.12.7)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (3.0.1)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)\n",
            "Installing collected packages: soupsieve, requests, html5lib, frozendict, cryptography, beautifulsoup4, yfinance\n",
            "  Attempting uninstall: requests\n",
            "    Found existing installation: requests 2.25.1\n",
            "    Uninstalling requests-2.25.1:\n",
            "      Successfully uninstalled requests-2.25.1\n",
            "  Attempting uninstall: html5lib\n",
            "    Found existing installation: html5lib 1.0.1\n",
            "    Uninstalling html5lib-1.0.1:\n",
            "      Successfully uninstalled html5lib-1.0.1\n",
            "  Attempting uninstall: beautifulsoup4\n",
            "    Found existing installation: beautifulsoup4 4.6.3\n",
            "    Uninstalling beautifulsoup4-4.6.3:\n",
            "      Successfully uninstalled beautifulsoup4-4.6.3\n",
            "Successfully installed beautifulsoup4-4.11.2 cryptography-39.0.1 frozendict-2.3.5 html5lib-1.1 requests-2.28.2 soupsieve-2.4 yfinance-0.2.12\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Y3bcwJb4rp93",
        "outputId": "b89dd5e7-d76d-4023-d05f-e6a158732d7b"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\r[*********************100%***********************]  1 of 1 completed\n"
          ]
        }
      ],
      "source": [
        "import yfinance as yf\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "from sklearn.preprocessing import MinMaxScaler\n",
        "from tensorflow.keras.models import Sequential\n",
        "from tensorflow.keras.layers import Dense, LSTM, Dropout\n",
        "\n",
        "\n",
        "########################################\n",
        "####Pick your ticker and time period####\n",
        "########################################\n",
        "stock_data = yf.download(\"TCEHY\", start=\"2001-01-01\", end=\"2022-02-24\")\n",
        "\n",
        "\n",
        "\n",
        "# Preprocess data\n",
        "scaled_data = np.array(stock_data[\"Close\"].pct_change().dropna()).reshape(-1,1)\n",
        "\n",
        "\n",
        "# Split data into training and test sets\n",
        "training_data_len = int(len(scaled_data) * 0.8)\n",
        "train_data = scaled_data[0:training_data_len, :]\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# 2.) Create your x_train/y_train data so that your RNN uses percentage change data to make a binary forecast where the stock moves up or down the next day\n",
        "# Build an RNN Architecture accordingly"
      ],
      "metadata": {
        "id": "foHoGy9hq3_o"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "x_train = []\n",
        "y_train = []\n",
        "\n",
        "\n",
        "#############################################################\n",
        "####Pick your input size and edit to make binary forecast####\n",
        "#############################################################\n",
        "input_size = 5\n",
        "for i in range(input_size, len(train_data)):\n",
        "    x_train.append(train_data[i-input_size:i, 0])\n",
        "    y_train.append(train_data[i, 0])\n",
        "\n",
        "\n",
        "x_train, y_train = np.array(x_train), np.array(y_train)\n",
        "x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))\n",
        "\n",
        "###################################\n",
        "####Build Your RNN Architecture####\n",
        "###################################\n",
        "model = Sequential()\n",
        "model.add(LSTM(x_train.shape[1], return_sequences=True, input_shape=(x_train.shape[1], 1)))\n",
        "model.add(LSTM(50, return_sequences=False))\n",
        "model.add(Dense(1))\n",
        "model.compile(optimizer='adam', loss='mean_squared_error')\n",
        "model.fit(x_train, y_train, batch_size=1, epochs=3)"
      ],
      "metadata": {
        "id": "5qGFB5HfqcVd",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "33040a56-6de6-4a39-9897-73bae7e5af60"
      },
      "execution_count": 30,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Epoch 1/3\n",
            "2439/2439 [==============================] - 23s 8ms/step - loss: 4.6288e-04\n",
            "Epoch 2/3\n",
            "2439/2439 [==============================] - 17s 7ms/step - loss: 4.5537e-04\n",
            "Epoch 3/3\n",
            "2439/2439 [==============================] - 16s 6ms/step - loss: 4.6024e-04\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "<keras.callbacks.History at 0x7f8270650a60>"
            ]
          },
          "metadata": {},
          "execution_count": 30
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# 3.) Test your model and compare insample Accurracy, insample random walk assumption Accuracy, Out of sample Accuracy and out of sample random walk assumption Accuracy using a bar chart"
      ],
      "metadata": {
        "id": "yFhO9vMjsWPk"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "test_data = scaled_data[training_data_len - input_size:, :]\n",
        "\n",
        "x_test = []\n",
        "y_test = np.array(stock_data[[\"Close\"]].pct_change().dropna())[training_data_len:, :]\n",
        "for i in range(input_size, len(test_data)):\n",
        "    x_test.append(test_data[i-input_size:i, 0])\n",
        "\n",
        "x_test = np.array(x_test)\n",
        "x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))\n",
        "\n",
        "predictions = model.predict(x_test)"
      ],
      "metadata": {
        "id": "r1Xj6Ji-rwnM",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "daed8bd7-f481-45af-80c2-ffd00feb3842"
      },
      "execution_count": 31,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "20/20 [==============================] - 2s 6ms/step\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Our model IN Accuracy\n",
        "predictions1 = model.predict(x_train)\n",
        "in_mse = np.mean((y_train - predictions1) ** 2)\n",
        "in_rmse = np.sqrt(np.mean((y_train - predictions1) ** 2))\n",
        "print(\"The in sample MSE and RMSE of our model are:\",in_mse,\"and\",in_rmse)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Tln49pR6HTNg",
        "outputId": "b83beded-fb4e-499d-ff55-7e85e6775c77"
      },
      "execution_count": 32,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "77/77 [==============================] - 0s 4ms/step\n",
            "The in sample MSE and RMSE of our model are: 0.0004474821020735927 and 0.02115377276217159\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#  Our model OSS Accuracy\n",
        "oss_mse = np.mean((y_test - predictions) ** 2)\n",
        "oss_rmse = np.sqrt(np.mean((y_test - predictions) ** 2))\n",
        "print(\"The out of sample MSE and RMSE of our model are:\",oss_mse,\"and\",oss_rmse)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "JDtN9wOHHTLL",
        "outputId": "afced2ac-f63b-44c8-dbc2-0961b0daaf21"
      },
      "execution_count": 33,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "The out of sample MSE and RMSE of our model are: 0.0006501751073909888 and 0.02549853147518478\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Random Walk Model IN Accuracy\n",
        "in_mse_rw = np.mean((y_train[1:] - y_train[:-1]) ** 2)\n",
        "in_rmse_rw = np.sqrt(np.mean((y_train[1:] - y_train[:-1]) ** 2))\n",
        "print(\"The in sample MSE and RMSE of Random Walk Model are:\",in_mse_rw ,\"and\",in_rmse_rw )\n",
        "\n",
        "# Random Walk Model OSS Accuracy\n",
        "oss_mse_rw = np.mean((y_test[1:] - y_test[:-1]) ** 2)\n",
        "oss_rmse_rw = np.sqrt(np.mean((y_test[1:] - y_test[:-1]) ** 2))\n",
        "print(\"The out of sample MSE and RMSE of Random Walk Model are:\",oss_mse_rw ,\"and\",oss_rmse_rw )"
      ],
      "metadata": {
        "id": "Mvo2INihZMhk",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "9233ec23-d836-4cdd-fe93-fe413de3d794"
      },
      "execution_count": 34,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "The in sample MSE and RMSE of Random Walk Model are: 0.0009003442376017356 and 0.030005736744858232\n",
            "The out of sample MSE and RMSE of Random Walk Model are: 0.0014990637617866352 and 0.03871774479210579\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import matplotlib.pyplot  as plt\n",
        "\n",
        "plt.bar([\"IN_MSE_Our Model\",\"IN_MSE_Random Walk Model\",],[in_mse,in_mse_rw])"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 284
        },
        "id": "2xzK1n7oM_uL",
        "outputId": "fb40052d-b331-487a-f334-9fce2acbd3e6"
      },
      "execution_count": 38,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "<BarContainer object of 2 artists>"
            ]
          },
          "metadata": {},
          "execution_count": 38
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 432x288 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYYAAAD5CAYAAAAjg5JFAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/NK7nSAAAACXBIWXMAAAsTAAALEwEAmpwYAAATW0lEQVR4nO3df7Rl5V3f8ffHGaG1qZgFY61AescwisMyYhjB0NTYkggU69hV0gxNKjFEtAuMpk0aaLqioU6bqVWqEaJUSFiUOFBM7F0LGtKGplEgwIXEJpAMuYsfBUxXhh/STmKgA9/+sZ+B89x17r3n3vlx78X3a627Zp9nP/s5zzN3n/PZ+9nn7JuqQpKkfb5lpTsgSVpdDAZJUsdgkCR1DAZJUsdgkCR11q90Bw6Eo446qqampla6G5K0ptx9992PV9WGueUviWCYmppiZmZmpbshSWtKkofHlTuVJEnqGAySpI7BIEnqGAySpI7BIEnqGAySpI7BIEnqGAySpI7BIEnqvCS++Sy9lE1ddONKd0Gr1EMfOOugtOsZgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpM1EwJDkjya4ks0kuGrP+8CTXtfV3JJkaWXdxK9+V5PTF2kxyWpJ7knw+yR8nOW4/xyhJWoJFgyHJOuAy4ExgM3BOks1zqp0HPFVVxwGXAjvatpuBbcAJwBnA5UnWLdLmh4A3V9WJwEeBf7lfI5QkLckkZwwnA7NV9UBVPQvsBLbOqbMVuLot3wCcliStfGdVPVNVDwKzrb2F2izg29vyEcCfLm9okqTlWD9BnaOBR0YePwqcMl+dqtqb5GngyFb+2TnbHt2W52vz7cBNSf4c+D/Aj4zrVJLzgfMBXvGKV0wwDEnSJFbjxed3An+3qo4BPgz8xrhKVXVFVW2pqi0bNmw4pB2UpJeySYLhMeDYkcfHtLKxdZKsZ5gCemKBbceWJ9kA/GBV3dHKrwNOnWgkkqQDYpJguAvYlGRjksMYLiZPz6kzDZzbls8GbqmqauXb2qeWNgKbgDsXaPMp4Igk39vaegPwpeUPT5K0VIteY2jXDC4EbgbWAVdV1b1JLgFmqmoauBK4Jsks8CTDGz2t3vXAfcBe4IKqeg5gXJut/GeBP0jyPENQvO2AjliStKAMB/Zr25YtW2pmZmaluyEdFFMX3bjSXdAq9dAHztqv7ZPcXVVb5pavxovPkqQVZDBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpYzBIkjoGgySpM1EwJDkjya4ks0kuGrP+8CTXtfV3JJkaWXdxK9+V5PTF2sxge5L7k3wpyTv2c4ySpCVYv1iFJOuAy4A3AI8CdyWZrqr7RqqdBzxVVccl2QbsAN6UZDOwDTgB+G7gvyX53rbNfG2+FTgWOL6qnk/ynQdioJKkyUxyxnAyMFtVD1TVs8BOYOucOluBq9vyDcBpSdLKd1bVM1X1IDDb2luozX8CXFJVzwNU1deWPzxJ0lJNEgxHA4+MPH60lY2tU1V7gaeBIxfYdqE2X8lwtjGT5L8k2TSuU0nOb3Vmdu/ePcEwJEmTWI0Xnw8HvllVW4D/AFw1rlJVXVFVW6pqy4YNGw5pByXppWySYHiMYc5/n2Na2dg6SdYDRwBPLLDtQm0+CnysLX8ceNUEfZQkHSCTBMNdwKYkG5McxnAxeXpOnWng3LZ8NnBLVVUr39Y+tbQR2ATcuUibfwj87bb8OuD+ZY1MkrQsi34qqar2JrkQuBlYB1xVVfcmuQSYqapp4ErgmiSzwJMMb/S0etcD9wF7gQuq6jmAcW22p/wAcG2SdwJ7gLcfuOFKkhazaDAAVNVNwE1zyt43svxN4I3zbLsd2D5Jm638z4CzJumXJOnAW40XnyVJK8hgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUsdgkCR1DAZJUmf9SndgpU1ddONKd0Gr1EMfOGuluyCtCM8YJEkdg0GS1DEYJEkdg0GS1DEYJEkdg0GS1DEYJEmdiYIhyRlJdiWZTXLRmPWHJ7murb8jydTIuotb+a4kpy+hzd9KsmeZ45IkLdOiwZBkHXAZcCawGTgnyeY51c4Dnqqq44BLgR1t283ANuAE4Azg8iTrFmszyRbg5fs5NknSMkxyxnAyMFtVD1TVs8BOYOucOluBq9vyDcBpSdLKd1bVM1X1IDDb2pu3zRYavwb88/0bmiRpOSYJhqOBR0YeP9rKxtapqr3A08CRC2y7UJsXAtNV9dWFOpXk/CQzSWZ27949wTAkSZNYVRefk3w38Ebgg4vVraorqmpLVW3ZsGHDwe+cJP0FMUkwPAYcO/L4mFY2tk6S9cARwBMLbDtf+Q8BxwGzSR4Cvi3J7IRjkSQdAJMEw13ApiQbkxzGcDF5ek6daeDctnw2cEtVVSvf1j61tBHYBNw5X5tVdWNVfVdVTVXVFPCNdkFbknSILHrb7aram+RC4GZgHXBVVd2b5BJgpqqmgSuBa9rR/ZMMb/S0etcD9wF7gQuq6jmAcW0e+OFJkpZqor/HUFU3ATfNKXvfyPI3Ga4NjNt2O7B9kjbH1HnZJP2TJB04q+risyRp5RkMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6hgMkqSOwSBJ6kwUDEnOSLIryWySi8asPzzJdW39HUmmRtZd3Mp3JTl9sTaTXNvKv5jkqiTfup9jlCQtwaLBkGQdcBlwJrAZOCfJ5jnVzgOeqqrjgEuBHW3bzcA24ATgDODyJOsWafNa4HjgB4C/DLx9v0YoSVqSSc4YTgZmq+qBqnoW2AlsnVNnK3B1W74BOC1JWvnOqnqmqh4EZlt787ZZVTdVA9wJHLN/Q5QkLcUkwXA08MjI40db2dg6VbUXeBo4coFtF22zTSH9Y+AT4zqV5PwkM0lmdu/ePcEwJEmTWM0Xny8HPlNVfzRuZVVdUVVbqmrLhg0bDnHXJOmla/0EdR4Djh15fEwrG1fn0STrgSOAJxbZdt42k/wysAH4uQn6J0k6gCY5Y7gL2JRkY5LDGC4mT8+pMw2c25bPBm5p1wimgW3tU0sbgU0M1w3mbTPJ24HTgXOq6vn9G54kaakWPWOoqr1JLgRuBtYBV1XVvUkuAWaqahq4ErgmySzwJMMbPa3e9cB9wF7ggqp6DmBcm+0pfwd4GLh9uH7Nx6rqkgM2YknSgiaZSqKqbgJumlP2vpHlbwJvnGfb7cD2Sdps5RP1SZJ0cKzmi8+SpBVgMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKljMEiSOgaDJKkzUTAkOSPJriSzSS4as/7wJNe19XckmRpZd3Er35Xk9MXaTLKxtTHb2jxsP8coSVqCRYMhyTrgMuBMYDNwTpLNc6qdBzxVVccBlwI72rabgW3ACcAZwOVJ1i3S5g7g0tbWU61tSdIhMskZw8nAbFU9UFXPAjuBrXPqbAWubss3AKclSSvfWVXPVNWDwGxrb2ybbZu/09qgtflTyx6dJGnJ1k9Q52jgkZHHjwKnzFenqvYmeRo4spV/ds62R7flcW0eCfxZVe0dU7+T5Hzg/PZwT5JdE4xFizsKeHylO7EaZMdK90DzcB9tDsA++jfGFU4SDKtSVV0BXLHS/XipSTJTVVtWuh/SfNxHD75JppIeA44deXxMKxtbJ8l64AjgiQW2na/8CeA7WhvzPZck6SCaJBjuAja1TwsdxnAxeXpOnWng3LZ8NnBLVVUr39Y+tbQR2ATcOV+bbZv/3tqgtfmflz88SdJSLTqV1K4ZXAjcDKwDrqqqe5NcAsxU1TRwJXBNklngSYY3elq964H7gL3ABVX1HMC4NttTvgfYmeRXgc+1tnXoOD2n1c599CDLcJAuSdLAbz5LkjoGgySpYzBIkjoGw0GSZE/7dypJJfmFkXW/neStC2z7kSTfSPJXR8r+fWvnqPb4vUnuTfI/k3w+ySmt/NPtHlSfbz83zPc8rf75Sb7cfu5M8tr9HPe+8f7qSNlRSf5fkt9eYlt7DkSdtWgt7D9JfiXJY63efUnOOQBD39f2Q/v6egDb/FySE9vy+iR7krxlZP3dSV69WJ/a7+SLizzXmn4dGAyHxteAX1ziDQFnabceSfItDLcKeaw9fg3wE8Crq+pVwOvpv0n+5qo6sf2czTyS/ATwc8Brq+p44OeBjyb5rkk7OfKdk1EPAmeNPH4jcO+YeprMqtx/mkur6sT2XL+b5FuX0MdD7Vbg1Lb8g8D9+x4n+SvAK4E/OYDPt2ZfBwbDobEb+BQvftdjEjuBN7XlH2PYqffdKuSvA49X1TMAVfV4Vf3pMvr1HuDdVfV4a+cehvtTXQD9UVuSLUk+3ZZ/Jck1SW4FrhnT7jeALyXZ9+3UNwHX71vZjqZuaUern0ryila+McntSb4weqTV1r07yV1tm/cvY6xr2Wrdf15QVV9h+L2/HCDJh5LMtLOSF35fbZ96f5J72u/5+FZ+ZJJPtvq/B2Rkm3+a5Ivt55da2VQ7y/1IkvuTXJvk9UluTfKVJCeP6eZtvBgMpwK/A5zYHp8M3F1VzyX5w3b2cG+GW+/MK8n3tDORHx6zes2+DgyGQ2cH8K4Md5adxP3AhiQvB85heKHv80ng2PaCuDzJ6+Zse+3IVMCvLfAcJwB3zymbaeWL2Qy8vqrmmz7YyfDlxmOB54DRN54PAle3o9Vrgd9q5b8JfKiqfgD46r7KSX6c4cuRJzO8kE9K8qMT9PGlZDXuPy9oUzBfqaqvtaL3tttWvAp4XZJXjVR/vKpeDXwIeFcr+2Xgj6vqBODjwL43yZOAn2G4l9qPAD+b5IfaNscBvw4c337+EfDa1ua/GNPN0TOGU4HPAM9kmHI7lSE4AN5WVScBW4B3JDlynjF/H/AHwFur6q55/mvW5OvAYDhEquoB4A6GnXdSH2P4suApwB+NtLUHOInhJoK7gevSzzmPTgW8e3/7Po/pqvrzBdZ/AngDQ/+vm7PuNcBH2/I1DC9mgL8J/P5I+T4/3n4+B9zD8Cawadk9X4NW8f7zziT3tr5tHyn/h0nuYfidncBwIDHaLxgOSqba8o8C/7H170aGW+7DsG98vKq+3vr9MeBvtXUPVtUXqup5himaT7W7J3xhpN0XVNXDwGFtqvR4YBfDXRhOYQiGW1vVdyT5E4YbgB7L+H1tA8NdGd5cVQtNP63J18GavYneGvWvGW4p/j8mrH8dw4vn6qp6Pnnh7Jr2DfJPA59O8gWGaYaPLLE/9zG8QdwyUnYSL86D7uXFg4e/NGfbry/UcFU9m+Ru4J8xvCn85IR9GveNywD/pqp+d8I2XqpW2/4DwzWGf5fkJ4Erk7ySYarqXcAPV9VTST5Cv/880/59jv17D3pmZPn5kcfPL9DubQxz/V+tqkryWYY34pOB25P8GMM1l9dU1Tfa9OncfR/gaeB/MbyZ3zdfB9fq68AzhkOoqr7MsBP9vQnrPwy8F7h8tDzJ9yUZPVI4EXh4GV36t8COfafKGT6x8daR53uIISgA/sEy2v914D1V9eSc8ttot00B3syLR7O3zinf52bgbUle1vp5dJLvXEZ/1rRVuP+MPtc0wzTkucC3Mxw4PJ3krzH8Qa7FfIZ2NpTkTNq1CoZ946eSfFuGC8R/n5Gzn2W4Dfgl4Pb2+Hbgp4H/XVVPM9wA9KkWCsczTF+N82zry08nWewsbs29DjxjOPS2M5wKTmSeo4OXAR9M8h0MR/WzvPi3KWCYI943zfN4Vb1+nrankxwN3JakgP8LvKWq9s1rvp/hKPBfMRxdLkm7/9W4T2H8AvDhJO9mmMr4mVb+iwyfinoPIzdPrKpPJvl+hiM6gD3AWxg+rfMXzarZf8a4hGFq5PtbH7/M8GmnWxfaqHk/8PttWuo2hqNxquqedsZxZ6v3e1X1uYz8+eAlupXhr0ze3tr/artus+/6wieAn0/yJYapps+ObWXY9usZPtn3X5PsaeE4rt6aex14ryRJUsepJElSx6mkFZTkMoYLX6N+s6o+fICf570MF9xG/aeq2j6uvtYG9x8dLE4lSZI6TiVJkjoGgySpYzBIkjoGgySp8/8BCY9+kgEYsJcAAAAASUVORK5CYII=\n"
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "plt.bar([\"OSS_MSE_Our Model\",\"OSS_MSE_Random Walk Model\",],[oss_mse,oss_mse_rw])"
      ],
      "metadata": {
        "id": "35O_7b3iX1cX",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 284
        },
        "outputId": "6cd7073f-c71a-4365-ef01-9659b072c490"
      },
      "execution_count": 39,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "<BarContainer object of 2 artists>"
            ]
          },
          "metadata": {},
          "execution_count": 39
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 432x288 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYYAAAD5CAYAAAAjg5JFAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/NK7nSAAAACXBIWXMAAAsTAAALEwEAmpwYAAAZQUlEQVR4nO3dfbRddX3n8ffHRPBpijZerRKYm0p8CONzpFU7rRSVoNbULhiT5VKsaNouUEdnqqHt0FksM5VhHJa2oIsOCONSQ4b6cGeMogWfFUjwkYdGr4AS6kMExIUWMPCdP84vcvbx3Nyd3Au5pO/XWlnZ+7d/+7f37959zmfv/Ttn31QVkiTt8oB9vQOSpIXFYJAkdRgMkqQOg0GS1GEwSJI6Fu/rHZgPj3zkI2tycnJf74Yk3a9cccUVP66qidHy/SIYJicn2bp1677eDUm6X0ny3XHl3kqSJHUYDJKkDoNBktRhMEiSOgwGSVKHwSBJ6jAYJEkdBoMkqcNgkCR17BfffJb2Z5PrP7avd0EL2PVvf/G8t+kVgySpw2CQJHUYDJKkDoNBktRhMEiSOgwGSVKHwSBJ6jAYJEkdBoMkqaNXMCRZlWRbkukk68csPzDJBW35ZUkmh5ad3Mq3JTl6qPzcJD9KcuUM2/xPSSrJI/eiX5KkvTRrMCRZBJwJHAOsANYmWTFS7QTglqo6DDgDOK2tuwJYAxwOrALOau0BnNfKxm3zEOCFwPf2sD+SpDnqc8VwBDBdVddW1Z3ARmD1SJ3VwPlt+kLgqCRp5Rur6o6qug6Ybu1RVZ8Dbp5hm2cAbwFqTzojSZq7PsFwMHDD0Pz2Vja2TlXtBG4FlvRctyPJauDGqvr6LPXWJdmaZOuOHTt6dEOS1MeCGnxO8hDgL4BTZqtbVWdX1cqqWjkxMXHv75wk/SvRJxhuBA4Zml/aysbWSbIYOAi4qee6wx4HLAO+nuT6Vv8rSX6jx35KkuZBn2DYAixPsizJAQwGk6dG6kwBx7fpY4FLqqpa+Zr2qaVlwHLg8pk2VFXfrKpHVdVkVU0yuPX0jKr6wR71SpK012YNhjZmcBJwEXANsKmqrkpyapKXtmrnAEuSTANvBta3da8CNgFXA58ATqyquwCSfBD4MvCEJNuTnDC/XZMk7Y1ef8GtqjYDm0fKThmavh04boZ1NwAbxpSv7bHdyT77J0maPwtq8FmStO8ZDJKkDoNBktRhMEiSOgwGSVKHwSBJ6jAYJEkdBoMkqcNgkCR1GAySpA6DQZLUYTBIkjoMBklSh8EgSeowGCRJHQaDJKnDYJAkdRgMkqQOg0GS1NErGJKsSrItyXSS9WOWH5jkgrb8siSTQ8tObuXbkhw9VH5ukh8luXKkrdOT/FOSbyT5cJKH7333JEl7atZgSLIIOBM4BlgBrE2yYqTaCcAtVXUYcAZwWlt3BbAGOBxYBZzV2gM4r5WN+hTw76rqKcC3gJP3sE+SpDnoc8VwBDBdVddW1Z3ARmD1SJ3VwPlt+kLgqCRp5Rur6o6qug6Ybu1RVZ8Dbh7dWFV9sqp2ttlLgaV72CdJ0hz0CYaDgRuG5re3srF12pv6rcCSnuvuzmuAj49bkGRdkq1Jtu7YsWMPmpQk7c6CHXxO8pfATuD945ZX1dlVtbKqVk5MTNy3OydJ+7E+wXAjcMjQ/NJWNrZOksXAQcBNPdf9FUleDbwEeEVVVY99lCTNkz7BsAVYnmRZkgMYDCZPjdSZAo5v08cCl7Q39ClgTfvU0jJgOXD57jaWZBXwFuClVfXz/l2RJM2HWYOhjRmcBFwEXANsqqqrkpya5KWt2jnAkiTTwJuB9W3dq4BNwNXAJ4ATq+ougCQfBL4MPCHJ9iQntLb+Dvg3wKeSfC3Je+apr5KkHhb3qVRVm4HNI2WnDE3fDhw3w7obgA1jytfOUP+wPvskSbp3LNjBZ0nSvmEwSJI6DAZJUofBIEnqMBgkSR0GgySpw2CQJHUYDJKkDoNBktRhMEiSOgwGSVKHwSBJ6jAYJEkdBoMkqcNgkCR1GAySpA6DQZLUYTBIkjp6BUOSVUm2JZlOsn7M8gOTXNCWX5ZkcmjZya18W5Kjh8rPTfKjJFeOtPXrST6V5Nvt/0fMoX+SpD00azAkWQScCRwDrADWJlkxUu0E4Jb295rPAE5r664A1gCHA6uAs1p7AOe1slHrgYurajlwcZuXJN1H+lwxHAFMV9W1VXUnsBFYPVJnNXB+m74QOCpJWvnGqrqjqq4Dplt7VNXngJvHbG+4rfOBP+zfHUnSXPUJhoOBG4bmt7eysXWqaidwK7Ck57qjHl1V32/TPwAe3WMfJUnzZEEPPldVATVuWZJ1SbYm2bpjx477eM8kaf/VJxhuBA4Zml/aysbWSbIYOAi4qee6o36Y5DGtrccAPxpXqarOrqqVVbVyYmKiRzckSX30CYYtwPIky5IcwGAweWqkzhRwfJs+Frikne1PAWvap5aWAcuBy2fZ3nBbxwMf7bGPkqR5MmswtDGDk4CLgGuATVV1VZJTk7y0VTsHWJJkGngz7ZNEVXUVsAm4GvgEcGJV3QWQ5IPAl4EnJNme5ITW1tuBFyT5NvD8Ni9Juo8s7lOpqjYDm0fKThmavh04boZ1NwAbxpSvnaH+TcBRffZLkjT/FvTgsyTpvmcwSJI6DAZJUofBIEnqMBgkSR0GgySpw2CQJHUYDJKkDoNBktRhMEiSOgwGSVKHwSBJ6jAYJEkdBoMkqcNgkCR1GAySpA6DQZLUYTBIkjoMBklSR69gSLIqybYk00nWj1l+YJIL2vLLkkwOLTu5lW9LcvRsbSY5KslXknwtyReSHDbHPkqS9sCswZBkEXAmcAywAlibZMVItROAW6rqMOAM4LS27gpgDXA4sAo4K8miWdp8N/CKqnoa8AHgr+bUQ0nSHulzxXAEMF1V11bVncBGYPVIndXA+W36QuCoJGnlG6vqjqq6Dphu7e2uzQJ+rU0fBPzz3nVNkrQ3FveoczBww9D8duC3ZqpTVTuT3AosaeWXjqx7cJueqc3XApuT/AvwU+C3x+1UknXAOoBDDz20RzckSX0sxMHnNwEvqqqlwHuB/zmuUlWdXVUrq2rlxMTEfbqDkrQ/6xMMNwKHDM0vbWVj6yRZzOAW0E27WXdseZIJ4KlVdVkrvwB4Tq+eSJLmRZ9g2AIsT7IsyQEMBpOnRupMAce36WOBS6qqWvma9qmlZcBy4PLdtHkLcFCSx7e2XgBcs/fdkyTtqVnHGNqYwUnARcAi4NyquirJqcDWqpoCzgHel2QauJnBGz2t3ibgamAncGJV3QUwrs1W/jrgH5LczSAoXjOvPZYk7VYGJ/b3bytXrqytW7fu692Q7hWT6z+2r3dBC9j1b3/xXq+b5IqqWjlavhAHnyVJ+5DBIEnqMBgkSR0GgySpw2CQJHUYDJKkDoNBktRhMEiSOgwGSVKHwSBJ6jAYJEkdBoMkqcNgkCR1GAySpA6DQZLUMesf6tnf+ax7zWQuz7mX7s+8YpAkdRgMkqQOg0GS1NErGJKsSrItyXSS9WOWH5jkgrb8siSTQ8tObuXbkhw9W5sZ2JDkW0muSfKGOfZRkrQHZh18TrIIOBN4AbAd2JJkqqquHqp2AnBLVR2WZA1wGvDyJCuANcDhwGOBf0zy+LbOTG2+GjgEeGJV3Z3kUfPRUUlSP32uGI4Apqvq2qq6E9gIrB6psxo4v01fCByVJK18Y1XdUVXXAdOtvd21+WfAqVV1N0BV/WjvuydJ2lN9guFg4Iah+e2tbGydqtoJ3Aos2c26u2vzcQyuNrYm+XiS5eN2Ksm6Vmfrjh07enRDktTHQhx8PhC4vapWAn8PnDuuUlWdXVUrq2rlxMTEfbqDkrQ/6xMMNzK457/L0lY2tk6SxcBBwE27WXd3bW4HPtSmPww8pcc+SpLmSZ9g2AIsT7IsyQEMBpOnRupMAce36WOBS6qqWvma9qmlZcBy4PJZ2vwIcGSb/j3gW3vVM0nSXpn1U0lVtTPJScBFwCLg3Kq6KsmpwNaqmgLOAd6XZBq4mcEbPa3eJuBqYCdwYlXdBTCuzbbJtwPvT/Im4DbgtfPXXUnSbHo9K6mqNgObR8pOGZq+HThuhnU3ABv6tNnKfwL4kBpJ2kcW4uCzJGkfMhgkSR0GgySpw2CQJHUYDJKkDoNBktRhMEiSOgwGSVKHwSBJ6jAYJEkdBoMkqcNgkCR1GAySpA6DQZLUYTBIkjoMBklSh8EgSeowGCRJHb2CIcmqJNuSTCdZP2b5gUkuaMsvSzI5tOzkVr4tydF70Oa7kty2l/2SJO2lWYMhySLgTOAYYAWwNsmKkWonALdU1WHAGcBpbd0VwBrgcGAVcFaSRbO1mWQl8Ig59k2StBf6XDEcAUxX1bVVdSewEVg9Umc1cH6bvhA4Kkla+caquqOqrgOmW3szttlC43TgLXPrmiRpb/QJhoOBG4bmt7eysXWqaidwK7BkN+vurs2TgKmq+n6/LkiS5tPifb0Dw5I8FjgOeF6PuuuAdQCHHnrovbtjkvSvSJ8rhhuBQ4bml7aysXWSLAYOAm7azbozlT8dOAyYTnI98JAk0+N2qqrOrqqVVbVyYmKiRzckSX30CYYtwPIky5IcwGAweWqkzhRwfJs+FrikqqqVr2mfWloGLAcun6nNqvpYVf1GVU1W1STw8zagLUm6j8x6K6mqdiY5CbgIWAScW1VXJTkV2FpVU8A5wPva2f3NDN7oafU2AVcDO4ETq+ougHFtzn/3JEl7qtcYQ1VtBjaPlJ0yNH07g7GBcetuADb0aXNMnYf12T9J0vzxm8+SpA6DQZLUYTBIkjoMBklSh8EgSeowGCRJHQaDJKnDYJAkdRgMkqQOg0GS1GEwSJI6DAZJUofBIEnqMBgkSR0GgySpw2CQJHUYDJKkDoNBktRhMEiSOnoFQ5JVSbYlmU6yfszyA5Nc0JZflmRyaNnJrXxbkqNnazPJ+1v5lUnOTfLAOfZRkrQHZg2GJIuAM4FjgBXA2iQrRqqdANxSVYcBZwCntXVXAGuAw4FVwFlJFs3S5vuBJwJPBh4MvHZOPZQk7ZE+VwxHANNVdW1V3QlsBFaP1FkNnN+mLwSOSpJWvrGq7qiq64Dp1t6MbVbV5mqAy4Glc+uiJGlP9AmGg4Ebhua3t7KxdapqJ3ArsGQ3687aZruF9ErgE+N2Ksm6JFuTbN2xY0ePbkiS+ljIg89nAZ+rqs+PW1hVZ1fVyqpaOTExcR/vmiTtvxb3qHMjcMjQ/NJWNq7O9iSLgYOAm2ZZd8Y2k/w1MAH8SY/9kyTNoz5XDFuA5UmWJTmAwWDy1EidKeD4Nn0scEkbI5gC1rRPLS0DljMYN5ixzSSvBY4G1lbV3XPrniRpT816xVBVO5OcBFwELALOraqrkpwKbK2qKeAc4H1JpoGbGbzR0+ptAq4GdgInVtVdAOPabJt8D/Bd4MuD8Ws+VFWnzluPJUm71edWElW1Gdg8UnbK0PTtwHEzrLsB2NCnzVbea58kSfeOhTz4LEnaBwwGSVKHwSBJ6jAYJEkdBoMkqcNgkCR1GAySpA6DQZLUYTBIkjoMBklSh8EgSeowGCRJHQaDJKnDYJAkdRgMkqQOg0GS1GEwSJI6DAZJUofBIEnq6BUMSVYl2ZZkOsn6McsPTHJBW35ZksmhZSe38m1Jjp6tzSTLWhvTrc0D5thHSdIemDUYkiwCzgSOAVYAa5OsGKl2AnBLVR0GnAGc1tZdAawBDgdWAWclWTRLm6cBZ7S2bmltS5LuI32uGI4Apqvq2qq6E9gIrB6psxo4v01fCByVJK18Y1XdUVXXAdOtvbFttnV+v7VBa/MP97p3kqQ9trhHnYOBG4bmtwO/NVOdqtqZ5FZgSSu/dGTdg9v0uDaXAD+pqp1j6nckWQesa7O3JdnWoy+a3SOBH+/rnVgIctq+3gPNwGN0yByP0387rrBPMCxIVXU2cPa+3o/9TZKtVbVyX++HNBOP0Xtfn1tJNwKHDM0vbWVj6yRZDBwE3LSbdWcqvwl4eGtjpm1Jku5FfYJhC7C8fVroAAaDyVMjdaaA49v0scAlVVWtfE371NIyYDlw+UxttnU+3dqgtfnRve+eJGlPzXorqY0ZnARcBCwCzq2qq5KcCmytqingHOB9SaaBmxm80dPqbQKuBnYCJ1bVXQDj2mybfCuwMcnbgK+2tnXf8facFjqP0XtZBifpkiQN+M1nSVKHwSBJ6jAYJEkdBsM8SLI0yUeTfDvJd5K8c9cznpI8JMn7k3wzyZVJvpDkYW3ZXya5Ksk3knwtyegXB4e38Zkk32vfDt9V9pEkt7XpByR5V9vGN5NsaZ8EI8n1rexr7d+7drOdJPmr1pdvJfl0ksPn+PN5XpJK8tqhsqe1sv+8B+1MJrlyrnUWov3sGDovyXWt3teTHDWPP6fb5qut1l6S/DjJI9r8Y9px+TtDdXYkWTLbPrXj/P/Nsr37xWvhfvsFt4Wivcg+BLy7qlZn8Byos4ENwJ8DbwR+WFVPbvWfAPwiybOBlwDPqKo7kjwSmO2BgT8Bngt8IcnDgccMLXs58FjgKVV1d5KlwM+Glh9ZVX2+LXoi8BzgqVX18yQvBKaSHF5Vt/dYnySLh769vsuVwH8A/lebXwt8vU97+7v98BgC+POqujDJka0vy3uud5+qqkpyKfBsYDODY/+r7f8vtJ/1TVV10zxudsG/FrximLvfB26vqvcCtI/jvgl4TZKHMHjh/fJLelW1raruaOU/btNU1Y+r6p9n2dZG2keBgT9i8Gayy2OA71fV3a297VV1y170563ASVX189bOJ4EvAa+A7hlbkmOTnNemz0vyniSXAf99TLvfBR6U5NHtjXAV8PGhtp6W5NJ25vvhoTO4Z7azzq8zCK1d9RclOb2d1X4jyZ/sRV8Xiv3tGBr2ZYYea9OuUK5oVznrhspvS7Kh/a4vTfLoVr4syZfb1crbhuqn/f53Xd28vJU/L8lnM7j6ujbJ25O8Isnlrd7jxuzjlxgEAe3/MxgExa75LyZ5WJKLk3yltTP6vLiOJM9K8tUZtrfgXwsGw9wdDlwxXFBVPwW+BxwGnAu8tR3cb0uy68zpk8AhGdyuOSvJ7/XY1sXA77YzyjXABUPLNgF/kMHl+zuSPH1k3U/nntsAbxrXeJJfAx5aVdeOLNra+jmbpcBzqurNMyy/EDiOwYvtK8AdQ8v+N/DWqnoK8E3gr1v5e4HXV9VTR9o6Abi1qp4FPAt4Xdptj/uh/eYYGmMV8JGh+ddU1TOBlcAbcs8tmocCl7bf8+eA17XydzK4knoy8P2hdv4IeBrwVOD5wOlJdl39PBX4U+BJwCuBx1fVEQzO0F8/Zh+/yD3BcATwYe55MsNzGATH7cDLquoZwJHAO9qb+q9I8hzgPcDqqvrO+B/Lwn4tGAz3sqr6GvCbwOnArwNbkjypqm4DnsngQYA7gAuSvHqW5u4CvsDgBf3gqrp+aDvbgScAJwN3Axene2/3yKp6Wvt3xnz0bYz/s+sLjDPYxODFsBb44K7CJAcBD6+qz7ai8xm8eT28lX+ulb9vqK0XAq9K8jXgMgYPYFyQtyvm6n56DJ2e5FvAB2iP4W/e0M54L2Xw5rvrd3YnsOv+/BXAZJt+LvccK8O//98BPlhVd1XVD4HPMnhTBNhSVd9vV1LfYRCgMHiTneRXbQGenuShwAPbz/XaJIfRrhiAAP8tyTeAf2RwFfToMW09icGtsz+oqu+N+8E0C/q14BjD3F3NPY/wAH555n0og8eM0w60DwEfSnI38CLgmvYm+hngM0m+yeARIOfNsr2NDM5o/uvogvZC+Djw8SQ/ZPDI8ov7dqSqfprkZ0l+c+Sq4ZkMXngAw9+IfNBIEz9jN6rqB0l+AbyAwX3z5+yu/izC4Ozpok7h0B+Juh/Zb46hIbvGGF7P4IrnmUmex+Ds/tlt/Ooz3HMM/aLu+bbtXXTfm/b0W7jDZ993D83fzZj3vLYv3wZew+DsHQbB9SLgUcA2Bj/XCeCZVfWLJNfzq8c/DK5qHgQ8HZjxtt5Cfy14xTB3FwMPSfIq+OUfNnoHcF474J47dI/wAAZ/mOi7SZ4wdEsABpfF3+2xvc8Df8PQWUZr+xlJHtumHwA8pWd7o04H3pXkwa2t5zM4O/tAW/7DJE9q23jZXrR/CoPL5F9eWVTVrcAtSf59K3ol8Nmq+gnwk9zzCZFXDLVzEfBnSR7Y9vPx7Yzv/mh/O4aG/R3wgAz+euNBDP6g18+TPBH47R7rf5F7xkSGf/+fB17e7q9PAL/L4Dlse+tLwH9kMCZC+/+NDG5vVdv3H7VQOJIZHlfNYHD/xcDftCDcnQX7WvCKYY7apxpexuCv0/0XBmG7GfiLVuVxwLvb/cgHAB8D/gF4BvC37RJxJ4Mzw3XMoh2k/2PMokcBf5/kwDZ/OYMX5S6fTrLrAPxGVb1qhk38LfAI4Jut/g8Y3Cv9l7Z8PYNL/h0Mxh4eNts+j+z/l2ZYdDzwngwGW68F/riV/zFwbpLinlsCMLhfPAl8pf1sd3A//aNO++ExNNq3twFvYXAG/qdJrmFwFn7pblceeCPwgSRvpftAzQ8zGCD+OoMrire0s/An9mhznC+2be0Khq8wGDPb9cmh9wP/t12VbQX+aaaGquqHSV7C4KrrNVV12Qz1FuxrwWclSZI6vJUkSerwVtICk+TDwOhHzd46OrA0D9s5k8EnPoa9c9dn6XX/5TGkufJWkiSpw1tJkqQOg0GS1GEwSJI6DAZJUsf/B6HqQSHTb84oAAAAAElFTkSuQmCC\n"
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "ZP_GJ8X-Wkln"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "# 4.) Plot in and out of sample accuracy\n",
        "# No more"
      ],
      "metadata": {
        "id": "8bncNwh8tKiE"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# Make predictions on full dataset\n",
        "\n",
        "test_predict = model.predict(x_test)\n",
        "test_predictions = (test_predict+1).reshape(1,-1) * np.cumprod(y_test+1)\n",
        "\n",
        "train_predict = model.predict(x_train)\n",
        "train_predictions = (train_predict+1).reshape(1,-1) * np.cumprod(y_train+1)\n",
        "\n",
        "\n",
        "\n",
        "plt.plot(stock_data[:training_data_len- input_size].index, np.cumprod(y_train+1), label=\"Training Data\")\n",
        "plt.plot(stock_data[:training_data_len- input_size].index, train_predictions[0], label=\"Training Predictions\")\n",
        "end_val = np.cumprod(y_train+1)[-1]\n",
        "test_predict = model.predict(x_test)\n",
        "test_predictions = (test_predict+1).reshape(1,-1) * (np.cumprod((y_test+1))*end_val)\n",
        "plt.plot(stock_data[training_data_len+1:].index, np.cumprod((y_test+1))*end_val,label=\"Test Data\")\n",
        "plt.plot(stock_data[training_data_len+1:].index, test_predictions[0], label=\"Test Predictions\")\n",
        "plt.xlabel(\"Date\")\n",
        "plt.ylabel(\"Stock Price\")\n",
        "plt.legend()\n",
        "plt.show()"
      ],
      "metadata": {
        "id": "d698mdExtfHp"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "#5.) Write an observation/conclusion about the graphs from Q4 and Q3"
      ],
      "metadata": {
        "id": "bK_jyyEEtTUB"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "I can find that our model has a better performance than the random walk model. As you can see, the bar chart shows our model has smaller mean squared error and also smaller sqrt mean squarred error. I think it is because that the price of Tencent has certain parttern and trend rather than just random walking"
      ],
      "metadata": {
        "id": "e90dFysUN3VY"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "# 6.) Create a parameter for number of lags in your input layer. Do a 3-fold CV to test three different time lags. i.e. Tested using 5,10,20 days of previous price data to forecast"
      ],
      "metadata": {
        "id": "pFtrp-lmtw6t"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "from sklearn.model_selection import GridSearchCV\n",
        "from keras.wrappers.scikit_learn import KerasClassifier\n",
        "from keras.wrappers.scikit_learn import KerasRegressor\n",
        "\n",
        "# Define the Keras model\n",
        "\n",
        "def create_model(input_size):\n",
        "    model = Sequential()\n",
        "    model.add(Dense(10, input_dim=input_size, activation='relu'))\n",
        "    model.add(Dense(1, activation='sigmoid'))\n",
        "    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])\n",
        "    return(model)\n",
        "\n",
        "# Wrap the Keras model in a scikit-learn compatible estimator，for us to use scikit-learn's tools for hyperparameter tuning, cross-validation, and evaluation.\n",
        "model = KerasRegressor(build_fn=create_model, verbose=0)\n",
        "\n",
        "# Define the hyperparameters to search over\n",
        "param_grid = {'epochs': [10, 100], 'input_size':[5,15,20]}\n",
        "\n",
        "# Perform the grid search over the hyperparameters\n",
        "grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)\n",
        "grid_result = grid.fit(x_train, y_train)\n",
        "\n",
        "# Print the results\n",
        "print(\"Best: %f using %s\" % (grid_result.best_score_, grid_result.best_params_))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "kEOQ6TO0-Fnw",
        "outputId": "7eddc1d6-7cc5-4037-bb4e-ab44785e031e"
      },
      "execution_count": 47,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "<ipython-input-47-e4ac251b3840>:15: DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.\n",
            "  model = KerasRegressor(build_fn=create_model, verbose=0)\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "12 fits failed out of a total of 18.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileu7foqrpa.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_20\" is incompatible with the layer: expected shape=(None, 15), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileu7foqrpa.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_21\" is incompatible with the layer: expected shape=(None, 15), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileu7foqrpa.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_22\" is incompatible with the layer: expected shape=(None, 15), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileu7foqrpa.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_23\" is incompatible with the layer: expected shape=(None, 20), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileu7foqrpa.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_24\" is incompatible with the layer: expected shape=(None, 20), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileu7foqrpa.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_25\" is incompatible with the layer: expected shape=(None, 20), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileawyehe6i.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_20\" is incompatible with the layer: expected shape=(None, 15), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileawyehe6i.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_21\" is incompatible with the layer: expected shape=(None, 15), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileawyehe6i.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_22\" is incompatible with the layer: expected shape=(None, 15), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileawyehe6i.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_23\" is incompatible with the layer: expected shape=(None, 20), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileawyehe6i.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_24\" is incompatible with the layer: expected shape=(None, 20), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "1 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/wrappers/scikit_learn.py\", line 175, in fit\n",
            "    history = self.model.fit(x, y, **fit_args)\n",
            "  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "    raise e.with_traceback(filtered_tb) from None\n",
            "  File \"/tmp/__autograph_generated_fileawyehe6i.py\", line 15, in tf__train_function\n",
            "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
            "ValueError: in user code:\n",
            "\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n",
            "        return step_function(self, iterator)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n",
            "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n",
            "        outputs = model.train_step(data)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1023, in train_step\n",
            "        y_pred = self(x, training=True)\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
            "        raise e.with_traceback(filtered_tb) from None\n",
            "    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
            "        raise ValueError(\n",
            "\n",
            "    ValueError: Input 0 of layer \"sequential_25\" is incompatible with the layer: expected shape=(None, 20), found shape=(None, 5, 1)\n",
            "\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_search.py:969: UserWarning: One or more of the test scores are non-finite: [-0.08384282         nan         nan -0.00879525         nan         nan]\n",
            "  warnings.warn(\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Best: -0.008795 using {'epochs': 100, 'input_size': 5}\n"
          ]
        }
      ]
    }
  ]
}